name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - gh-418

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    env:
      NPM_TOKEN: ${{ secrets.NPM_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          ref: ${{ github.head_ref }}
          node-version: 20

      - name: Install Dependencies
        run: yarn
        env:
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Vite Project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build